# Generated by Django 4.1.1 on 2022-09-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_customdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomDocument',
        ),
    ]
